[agent]
  flush_interval = "5s"
  debug = true

[[inputs.gnmi]]
  addresses = ["172.20.20.4:6030"]

  username = "admin"
  password = "admin"

  encoding = "json_ietf"
  tls_enable = false
  redial = "10s"

  [[inputs.gnmi.subscription]]
    name = "interface_status"
    path = "/interfaces/interface[name=Ethernet2]/state/oper-status"
    subscription_mode = "on_change"

  [[inputs.gnmi.subscription]]
    name = "interface_in_octets"
    path = "/interfaces/interface[name=Ethernet2]/state/counters/in-octets"
    subscription_mode = "sample"
    sample_interval = "5s"

  [[inputs.gnmi.subscription]]
    name = "interface_out_octets"
    path = "/interfaces/interface[name=Ethernet2]/state/counters/out-octets"
    subscription_mode = "sample"
    sample_interval = "5s"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "NetPilot"
  bucket = "telemetry"
